version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
  api:
    build: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "5000:80"
